---
name: Workflow Linter

on:
  pull_request:
    paths:
      - .github/workflows/**

jobs:
  call-workflow:
    uses: bitwarden/gh-actions/.github/workflows/workflow-linter.yml@68bdffd3e8e4740360af973c1bc9dac01a9193ed
